# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

cppPSO <- function(OBJ_FUNC, PSO_INFO_LIST, env, IF_PARALLEL, VERBOSE) {
    .Call(`_globpso_cppPSO`, OBJ_FUNC, PSO_INFO_LIST, env, IF_PARALLEL, VERBOSE)
}

